Remove assertions on null-vs.-dftime inequalities
This partially reverts commit 071d5970f460584af817802b7ea07103fb7f5088.

I had mistakenly assumed Python treated binary operations with None as SQL
does with NULL.  Instead of None values propagating, Python 2 and 3 each
have their semantics, both different from SQL.  Session transcripts follow.

I had missed this in the regression tests because of finding another error
earlier in a nearby regression test.  I mistook the stack trace for the
other error.

OS X Lion 2.7.1:
>>> None > 2
False
>>> 2 > None
True

3.2.2:
>>> None > 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  TypeError: unorderable types: NoneType() > int()
>>> 3 > None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  TypeError: unorderable types: int() > NoneType()